[profile.default]
fs_permissions = [
    { access = "read-write", path = "./script/output/" },
    { access = "read", path = "./script/input/" },
]
libs = ["lib"]
out = "out"
src = "src"
viaIR = true
# For Surl https://github.com/memester-xyz/surl
ffi = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
